#! /usr/bin/env python3
import http.client
import json

def main():
    conn = http.client.HTTPConnection('api.ntv.com.tr')
    conn.request('GET', '/Finance?code=USD%2FTRL&period=daily')
    resp = conn.getresponse()
    if resp.status == 200:
        data = json.loads(resp.read().decode('utf-8'))
        try:
            data_time = data['data']['xAxisData'][-1]
            data_value = data['data']['yAxisData'][-1]
            print("%s (@%s)" % (data_value, data_time))
        except IndexError:
            print("NO DATA")
    else:
        print("ERROR: %s", res.status, resp.reason)

if __name__ == "__main__":
    main()
