#! /usr/bin/env python3
import http.client
import json

ST = b'''<span data-type="son_fiyat" data-secid="USDTRY Curncy">'''

def main():
    conn = http.client.HTTPConnection('www.bloomberght.com')
    conn.request('GET', '/')
    resp = conn.getresponse()
    if resp.status == 200:
        text = resp.read()
        i0 = text.find(ST)
        i1 = text.find(b'<', i0 + len(ST))
        print(text[i0+len(ST):i1].decode('utf-8'))
    else:
        print("ERROR:", resp.status, resp.reason)

if __name__ == "__main__":
    main()
