
[editor]
mouse = false
bufferline = "always"
cursorline = true
continue-comments = false
auto-completion = false
color-modes = true
true-color = true

[editor.soft-wrap]
enable = true

[editor.whitespace]
#render.newline = "all"

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
#character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
character = "┆" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.lsp]
# Disable automatically popups of signature parameter help
auto-signature-help = false
# Show LSP messages in the status line
display-messages = true

#[keys.normal]
#X = "select_line_above"
#x = ["collapse_selection", "delete_selection"]
#"A-x" = ["collapse_selection", "delete_selection_noyank"]
#l = "extend_line_below"
#L = "extend_line_above"
#"A-l" = "copy_selection_on_next_line"
#D = "kill_to_line_end"
#C = ["kill_to_line_end", "insert_mode"]
#"C-x" = "completion"
#"C-/" = "toggle_comments"
#"0" = "goto_first_nonwhitespace"
#"i" = ["collapse_selection", "insert_mode"]

[keys.insert]
pageup = "no_op"
pagedown = "no_op"
